name: DarkLabyrinth
main: DarkLabyrinth\main
version: 1.0.0
api:
  - 3.0.0
  - 3.0.0-ALPHA7
  - 3.0.0-ALPHA8
  - 3.0.0-ALPHA9
  - 3.0.0-ALPHA10
  - 3.0.0-ALPHA11
  - 4.0.0
load: POSTWORLD
author: siropan

commands:
  killer:
    description: 鬼決め
    permission: op
  timer:
    description: タイマー
    permission: op